Update D-05-interconnection-via-network.yml

diff --git a/.github/workflows/D-05-interconnection-via-network.yml b/.github/workflows/D-05-interconnection-via-network.yml
--- a/.github/workflows/D-05-interconnection-via-network.yml
+++ b/.github/workflows/D-05-interconnection-via-network.yml
@@ -49,6 +49,16 @@ jobs:
             echo "Container failed with exit status $CONTAINER_STATUS"
             exit 1
           fi
+          
+      - name: Check exit status
+        run: |
+          CONTAINER_STATUS=$(docker inspect postgres-client --format='{{.State.ExitCode}}')
+          if [ "$CONTAINER_STATUS" -eq 0 ]; then
+            echo "Container exited successfully"
+          else
+            echo "Container failed with exit status $CONTAINER_STATUS"
+            exit 1
+          fi
       
       - name: Setup tmate session
         if: ${{ failure() }}
