Update K-15-helm-chart.yml

diff --git a/.github/workflows/K-15-helm-chart.yml b/.github/workflows/K-15-helm-chart.yml
--- a/.github/workflows/K-15-helm-chart.yml
+++ b/.github/workflows/K-15-helm-chart.yml
@@ -79,7 +79,15 @@ jobs:
       
    - name: Check PSQL connection
      run: |
-       ./check_exit_code_and_logs.sh  'pg_isready -h localhost'
+        ./check_exit_code_and_logs.sh  'psql postgresql://md_dterteac:${{ secrets.PSQL_PASSWORD }}@localhost:${{ env.PSQL_PORT }}/demodb'
+        CONNECTION_CHECK=$(pg_isready -h localhost -p 6432)
+        ./check_exit_code_and_logs.sh "$CONNECTION_CHECK"
+        if [[ "${{ env.CONNECTION_CHECK }}" == *"accepting connections"* ]]; then
+            echo "The connection is up"
+          else
+           echo "The connection is failed"
+           exit 1
+          fi
    
    - name: Setup tmate session
      if: ${{ failure() }}
